baseURL = 'https://mi-ki-ri.github.io/official2021/'
languageCode = 'en-us'
title = 'Mikirihassha P Official 2021~'
theme = "2021"

[params]
    subtitle = "Music, Book, Songwriting"

[taxonomies]
    tag = "tags"
    category = "categories"
